# Generated by Django 4.0.6 on 2022-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location_room',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=10, unique=True),
        ),
    ]
