# Generated by Django 4.0.6 on 2022-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'Paypal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('EL', 'Eliminado')], max_length=20),
        ),
    ]
