# Generated by Django 4.0.6 on 2022-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_details',
            new_name='room',
        ),
    ]
